prototype3/myshop3/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

prototype3/myshop3/myshop3/urls.py
from django.conf.urls import include, url
from django.urls import reverse, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='login/index.html')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prototype3/myshop3/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

prototype3/myshop3/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^show_orders/$', views.show_orders, name='show_orders'),
]

prototype3/myshop3/cart/models.py
from django.db import models

# Create your models here.

prototype3/myshop3/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

prototype3/myshop3/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

prototype3/myshop3/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}


{% block card %}
    <div id="current-position-of-order">
        <div id="current-position-of-order-line"></div>

        <div id="current-position-of-order-card"></div>
        <p id="current-position-of-order-card-title">Корзина</p>
        <p id="current-position-of-order-card-1">1</p>
        <div id="current-position-of-order-ordering"></div>
        <p id="current-position-of-order-ordering-title">Оформление заказа</p>
        <p id="current-position-of-order-ordering-2">2</p>
        <div id="current-position-of-order-payment"></div>
        <p id="current-position-of-order-payment-title">Оплата</p>
        <p id="current-position-of-order-payment-3">3</p>
        <div id="current-position-of-order-finish"></div>
        <p id="current-position-of-order-finish-title">Завершение</p>
        <p id="current-position-of-order-finish-4">4</p>
    </div>
    {% for item in cart %}
            {% with product=item.product %}
                <div id="list-of-items">
                    <div id="line1"></div>
                    <div id="item1">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.main_image %}{{ product.main_image.url }}{% endif %}" height="230px" width="170px">
                        </a>
                    </div>
                    <p id="item1-name">{{ product.name }}</p>
                    <p id="item1-amount">Количество: {{ item.quantity }}</p>
                    <p id="item1-price">{{ item.price }} rub</p>
                    <div id="X">
                        <a href="{% url "cart:cart_remove" product.id%}">
                        <div id="X1"></div>
                        <div id="X2"></div>
                        </a>
                    </div>  
                </div>
                
            {% endwith %}
        {% endfor %}
    <div class="textblock-next">
        <!-- <div class="box1">
            <input type="text" name="index" placeholder="Есть наш промокод?">   
        </div> -->
        <div class="box2" >
            <form action="{% url 'shop:product_list' %}">
            <button class="button-additional">продолжить покупки</button>  
            </form>
        </div>
        <div class="box3">
            <p>Сумма заказа:</p>    
        </div>
        <div class="box4">
            <p>{{ cart.get_total_price }} rub</p>    
        </div>
        <div class="box5">
            <form action="{% url 'orders:order_create' %}">
            <button>перейти к оформлению</button>   
            </form>
        </div>
		
		
    </div>
	
    
	
	
{% endblock %}