prototype3/myshop3/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

prototype3/myshop3/myshop3/urls.py
from django.conf.urls import include, url
from django.urls import reverse, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='login/index.html')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prototype3/myshop3/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^show_orders/$', views.show_orders, name='show_orders'),
]

prototype3/myshop3/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list', args=[self.slug])


class Manufacturer(models.Model):
    name = models.CharField(max_length=45, help_text="Enter name of manufacturer")
    description = models.TextField(help_text="Enter description of manufacturer")
    email = models.EmailField(help_text="Enter email of user", blank=True)
    website = models.CharField(max_length=128, help_text="It is address of website", blank=True)

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    # Methods
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('manufacturer-detail', args=[str(self.id)])


class Product(models.Model):
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    manufacturer_id = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    main_image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    detail_image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

prototype3/myshop3/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from orders.models import Order, OrderItem
from cart.forms import CartAddProductForm


def main(request):
    category = None
    num_goods = Product.objects.all().count()
    num_categories = Category.objects.all().count()
    num_manufacturer = 0
    num_goods_available = Product.objects.filter(available=True).count()
    return render(request,
                  'shop/product/index.html',
                  {'num_goods': num_goods,
                   'num_categories': num_categories,
                   'num_manufacturer': num_manufacturer,
                   'num_goods_available': num_goods_available})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


def show_orders(request):
    orders = Order.objects.all()
    orders_item = OrderItem.objects.all()
    name_of_orders = request.user.first_name
    time_created = Order.created
    if not Order.paid:
        paid = "заказ оплачен"
    else:
        paid = "заказ не оплачен"
    return render(request, 'shop/product/orders.html', {'orders': orders, 'orders_item': orders_item,
                                                        'name_of_orders': name_of_orders, 'time_created': time_created,
                                                        'paid': paid})

prototype3/myshop3/shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <!-- <link href="css/styles1.css" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;600&display=swap" rel="stylesheet">
  <meta charset="utf-8">
  
 <!--  {% block title %}<title>Flaneur</title>{% endblock %} -->
 <title>Flaneur</title>
  <meta charset="utf-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

  <!-- Добавление дополнительного статического CSS файла-->

  
</head>

<body>
  <div id="fixed_nav">
  <div class="badges-menu">
  <nav class="icon-menu-left">
    <a href="{% url 'shop:product_list' %}"><img id="menu" class="badges" src="{% static 'images/MenuLines.png' %}"></a>
    <a href="#lefpanelmenu"><img id="magnifier" class="badges" src="{% static 'images/Magnigier.png' %}"></a>
  </nav>
  <nav class="icon-menu-right">
	
	{% if user.is_authenticated %}
    <a href="/accounts/logout" id="click-me"><img id="heart" class="badges" src="{% static 'images/account.png' %}"></a>
	<a href="{% url 'cart:cart_detail' %}"><img id="bucket" class="badges" src="{% static 'images/Bucket.png' %}"></a>
	{% else %}
    <a href="/accounts/login" id="click-me"><img id="heart" class="badges" src="{% static 'images/account.png' %}"></a>
	<a href="/accounts/login"><img id="bucket" class="badges" src="{% static 'images/Bucket.png' %}"></a>
	{% endif %}
	
    
	<div class="user">
    {% if user.is_authenticated %}
    <a href="#" id="user">{{ user.get_username }}</a>
    {% endif %}
  </div>
	
	{% if user.is_authenticated %}
	<a href="{% url 'shop:show_orders' %}" class="link">заказы</a>
	{% else %}
	<a href="/accounts/login" class="link">заказы</a>
	{% endif %}
  </nav>
  </div>

  <h1 id="logo_location"><a href="{% url 'shop:main' %}" id="logo_decoration">flaneur</a></h1>
  
  <nav class="menu">
    <div class="nav-link-wrapped">
      <a href="{% url 'shop:product_list' %}" id="chancellery">канцелярия</a>
    </div>
    <div class="nav-link-wrapped">
      <a href="{% url 'shop:product_list' %}">свечи</a>
    </div>
    <div class="nav-link-wrapped">
      <a href="{% url 'shop:product_list' %}">керамика</a>
    </div>
    <div class="nav-link-wrapped">
      <a href="{% url 'shop:product_list' %}">контакты</a>
    </div>
  </nav>
  </div>
  <br> <br>
  <!-- <div class="bg-modal">
    <div class="modal-content">
      <div class="close">+</div>
      <div class="enter">
        <h1>Войти</h1>
      </div>
      <div class="input-field2">
        <form action="">
        <input type="text" name="lastname" placeholder="e-mail">
        <input type="text" name="lastname" placeholder="Пароль" >
        </form>
        </div>
        <div class="button-field">
        <form action="payment-process.html">
          <button class="button">войти</button>
        </form>
      </div>
        <form action="payment-process.html">
          <button class="button">зарегистрироваться</button>
        </form>
      </div>
    </div>
    </div>
  </div> -->
  {% block orders %} {% endblock %}
  {% block create %} {% endblock %}
  {% block created %} {% endblock %}
  {% block password_reset %} {% endblock %}
  {% block verification_sent %} {% endblock %}
  {% block verified_email_required %} {% endblock %}
  {% block password_reset_done %} {% endblock %}
  {% block signup_closed %} {% endblock %}
  {% block password_change %} {% endblock %}
  {% block email_confirm %} {% endblock %}
  {% block password_reset_from_key_done %} {% endblock %}
  {% block account_inactive %} {% endblock %}

  {% block signup %} {% endblock %}
  {% block login %} {% endblock %}
  {% block logout %} {% endblock %}
  {% block card %} {% endblock %}
  {% block details %} {% endblock %}
  {% block catalog %} {% endblock %}
  {% block photos-content %}
  
  {% endblock %}
  <br><br>
  
  <div class="footer">
    <div class="delivery-and-payment">
      <a id="left-footer-content-delivery" href="#delivery">доставка и оплата</a>
    </div>
    <div class="exchange">
      <a id="left-footer-content-exchange" href="#exchange">обмен и возврат</a>
    </div>
    <div class="contacts">
      <a id="left-footer-content-contacts" href="#contacts">контакты</a>
    </div>
    <div class="follow-us">
      <p id="centre-footer-content-follow-us">follow us</p>
    </div>  
    <div class="insta-logo">
      <a href="https://www.instagram.com/chernykh.julia/" id="instagram"><img src="{% static 'images/instalogo.png' %}" id="centre-footer-content-instagram" width="20" height="20"></a>
    </div>
    <div class="news"> 
      <p id="right-footer-content-news">узнавайте о новинках первыми</p>
    </div>
    <div class="e-mail-entering">
      <input type="text" name="index" placeholder="e-mail">
    </div>
    <div class="button-field2">
      <button class="button2">подписаться</button>
    </div>
  </div>


  <!-- <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
	  <br></br>
      <ul class="sidebar-nav">
           <li><a href="{% url 'shop:main' %}">Домашняя страница</a></li> -->
          <!-- <li><a href="{% url 'shop:product_list' %}">Все товары</a></li> -->
      <!-- </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>
  </div> --> 

</body>
<script src="{% static 'function.js' %}"></script>
</html>

<!-- % url 'index' % -->